name: JoinTeleport
main: roi611\warp\Main
version: 1.3.0
api: 
- 4.0.0
- 5.0.0-ALPHA1
load: POSTWORLD
author: roi611
description: サーバーに入ったらconfigで設定した場所に移動します

commands:
 jotp:
    description: スポーン地点を設定します
    usage: /jotp
    permission: "jotp.command"

permissions:
 jotp.command:
  default: op
  