name: JoinTeleport
main: roi611\warp\Main
version: 1.0.1
api: 3.0.0
load: POSTWORLD
author: roi611
description: サーバーに入ったらconfigで設定した場所に移動します

commands:
 jotp:
  discription: スポーン地点を設定します
  usage: /jotp
  permission: "cmd.command"

permissions:
 cmd.command:
  default: op
  